import time
import sys

# Define lyrics with a simple time delay after each line (in seconds)
# For more complex timing, you would need to use an LRC file format and a dedicated parser.
# lyrics_with_timing = [
#     ("Line 1: Hello, world!", 2.0),
#     ("Line 2: This is a test of timed lyrics.", 1.5),
#     ("Line 3: The time module is essential.", 1.0),
#     ("Line 4: Enjoy the music!", 3.0),
# ]
# DeBÍ TiRAR MáS FOToS de cuando te tuve
# [01:27.72]Debí darte más besos y abrazos las veces que pude
# [01:33.88]Ey, ojalá que los míos nunca se muden
# [01:37.81]Y si hoy me emborracho, pues que me ayuden
def display_lyrics():
    # time.sleep(2.0) 
    # print("starting song...\n")
    # time.sleep(3.0)  # Simulate the time before the song starts
    print("De", end="", flush=True)
    time.sleep(0.30)
    print("bí", end=" ", flush=True)
    time.sleep(0.30)
    print("ti", end="", flush=True)
    time.sleep(0.30)
    print("rar", end=" ", flush=True)
    time.sleep(0.30)
    print("más", end=" ", flush=True)
    time.sleep(0.30)
    print("fo", end="", flush=True)
    time.sleep(0.20)
    print("tos", end=" ", flush=True)
    time.sleep(0.60)
    print("de", end=" ", flush=True)
    time.sleep(0.30)
    print("cuan", end="", flush=True)
    time.sleep(0.30)
    print("do", end=" ", flush=True)
    time.sleep(0.50)
    print("te", end=" ", flush=True)
    time.sleep(0.30)
    print("tu", end="", flush=True)
    time.sleep(0.30)
    print("ve", end="\n", flush=True)
    time.sleep(0.30)

    print("De", end="", flush=True)
    time.sleep(0.30)
    print("bí", end=" ", flush=True)   
    time.sleep(0.30)
    print("dar", end="", flush=True)
    time.sleep(0.30)
    print("te", end=" ", flush=True)
    time.sleep(0.30)
    print("más", end=" ", flush=True)
    time.sleep(0.30)
    print("be", end="", flush=True)
    time.sleep(0.30)
    print("sos", end=" ", flush=True)
    time.sleep(0.50)
    print("y", end=" ", flush=True)
    time.sleep(0.30)
    print("abra", end="", flush=True)
    time.sleep(0.30)
    print("zos", end=" ", flush=True)
    time.sleep(0.50)
    print("las", end=" ", flush=True)
    time.sleep(0.30)
    print("ve", end="", flush=True)
    time.sleep(0.20)
    print("ces", end=" ", flush=True)
    time.sleep(0.40)
    print("que", end=" ", flush=True)
    time.sleep(0.30)
    print("pu", end="", flush=True)
    time.sleep(0.40)
    print("de", end="\n", flush=True)
    time.sleep(0.90)

    print("Ey", end=" ", flush=True)
    time.sleep(0.60)
    print("o", end="", flush=True)
    time.sleep(0.20)
    print("ja", end="", flush=True)
    time.sleep(0.20)
    print("lá", end=" ", flush=True)
    time.sleep(0.20)
    print("que", end=" ", flush=True)
    time.sleep(0.20)
    print("los", end=" ", flush=True)
    time.sleep(0.20)
    print("mí", end="", flush=True)
    time.sleep(0.40)
    print("os", end=" ", flush=True)
    time.sleep(0.30)
    print("nun", end="", flush=True)
    time.sleep(0.15)
    print("ca", end=" ", flush=True)
    time.sleep(0.15)
    print("se", end=" ", flush=True)
    time.sleep(0.30)
    print("mu", end="", flush=True)
    time.sleep(0.60)
    print("den", end="\n", flush=True)
    time.sleep(0.50)

    print("Y", end=" ", flush=True)
    time.sleep(0.20)
    print("si", end=" ", flush=True)
    time.sleep(0.20)
    print("hoy", end=" ", flush=True)
    time.sleep(0.20)
    print("me", end=" ", flush=True)
    time.sleep(0.10)
    print("em", end="", flush=True)
    time.sleep(0.10)
    print("bo", end="", flush=True)
    time.sleep(0.10)
    print("rra", end="", flush=True)
    time.sleep(0.50)
    print("cho", end=", ", flush=True)
    time.sleep(0.50)
    print("pues", end=", ", flush=True)
    time.sleep(0.30)
    print("que", end=" ", flush=True)
    time.sleep(0.30) 
    print("me", end=" ", flush=True)
    time.sleep(0.30)
    print("ayuden", end="\n", flush=True)
    time.sleep(0.20)

if __name__ == "__main__":
    while True:
        display_lyrics()
